name: Python Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ['3.8', '3.9', '3.10']
        django: ['3.2', '4.0']
        wagtail: ['2.16', '3.0', '4.0']
        include:
          - wagtail: '2.15'
            django: '3.2'
            python: '3.7'
          - wagtail: '2.15'
            django: '3.2'
            python: '3.8'
          - wagtail: '2.15'
            django: '3.2'
            python: '3.9'
          - wagtail: '2.15'
            django: '3.2'
            python: '3.10'
          - wagtail: '4.0'
            django: '4.1'
            python: '3.8'
          - wagtail: '4.0'
            django: '4.1'
            python: '3.9'
          - wagtail: '4.0'
            django: '4.1'
            python: '3.10'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
          tox
      env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}